### ISSUE TITLE
CMS ML hackathon task: gun sample training

### ISSUE THREAD

**Issue by jpata** [jpata/particleflow#72]
Get a tagged version of the code:
```
git checkout master
git pull
git submodule init
git submodule update
```

Download the training data:
```bash
rsync -r --progress lxplus.cern.ch:/eos/user/j/jpata/mlpf/cms/tensorflow_datasets ~/
```
Run the training on the full model using just the ttbar sample
```
CUDA_VISIBLE_DEVICES=... python3 mlpf/pipeline.py train -c parameters/cms.yaml
```

Copy `cms.yaml` to `cms-withgun.yaml` and change as follows:
```
training_datasets:
  - cms_pf_ttbar
  - cms_pf_single_pi
  - cms_pf_single_electron

testing_datasets:
  - cms_pf_ttbar
  - cms_pf_single_pi
  - cms_pf_single_electron
```

Train again
```
CUDA_VISIBLE_DEVICES=... python3 mlpf/pipeline.py train -c parameters/cms-withgun.yaml
```

Note that the training is set currently for 1000 epochs, which you may want to abort early.

Look at the validation plots in `experiments/cms*/history/epoch_N/...`, especially the energy correlation plots under `cls_2/energy_cls2*`

**Comment by jpata** [comment]
The results were uploaded here: https://indico.cern.ch/event/1082584/contributions/4552631/attachments/2320256/3950875/gunSample-Sept30-2021.pdf

We can conclude that gun sample training does help rare particles, but needs to be combined with physical samples. Using a mixed dataset of gun samples and physical samples is now the default in #84 and is implemented as follows in `cms.yaml`:

```yaml
train_test_datasets:
  physical: 
    batch_per_gpu: 5
    datasets:
      - cms_pf_ttbar
      - cms_pf_ztt
  gun: 
    batch_per_gpu: 100
    datasets:
      - cms_pf_single_pi 
      - cms_pf_single_pi0
      - cms_pf_single_tau
      - cms_pf_single_electron
      - cms_pf_single_mu
      - cms_pf_single_gamma
```

I consider this issue resolved.
Thank you for the studies @jieunyoo!
